# Generated by Django 6.1.1 on 2026-09-04 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ROLE_DEFAULT_TABS = {
    'Admin': ['cheques', 'containers', 'customers', 'dashboard', 'sales', 'settings', 'users'],
    'Operations': ['containers', 'customers', 'dashboard', 'sales'],
    'Finance': ['cheques', 'customers', 'dashboard', 'settings'],
    'Gatekeeper': ['sales'],
}


def seed_existing_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in User.objects.prefetch_related('groups'):
        tabs = set()
        if user.is_superuser:
            tabs.update(ROLE_DEFAULT_TABS['Admin'])
        else:
            for role in user.groups.values_list('name', flat=True):
                tabs.update(ROLE_DEFAULT_TABS.get(role, []))
        UserProfile.objects.get_or_create(user=user, defaults={'allowed_tabs': sorted(tabs)})


def delete_seeded_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_tabs', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.RunPython(seed_existing_user_profiles, delete_seeded_user_profiles),
    ]
