# Generated by Django 6.1.1 on 2026-09-05 18:42

from django.db import migrations, models


ALL_TABS = ['cheques', 'containers', 'customers', 'dashboard', 'sales', 'settings', 'users']
PERMANENT_ADMIN_USERNAME = 'admin'


def migrate_allowed_tabs_to_tab_permissions(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    User = apps.get_model('auth', 'User')
    full_permissions = {tab: 'full' for tab in ALL_TABS}
    for profile in UserProfile.objects.select_related('user'):
        if profile.user.username == PERMANENT_ADMIN_USERNAME or profile.user.is_superuser:
            profile.tab_permissions = full_permissions
        elif profile.allowed_tabs:
            profile.tab_permissions = {
                tab: 'full' if tab in profile.allowed_tabs else 'none'
                for tab in ALL_TABS
            }
        else:
            profile.tab_permissions = {}
        profile.save(update_fields=['tab_permissions'])

    for user in User.objects.filter(username=PERMANENT_ADMIN_USERNAME):
        changed_fields = []
        if not user.is_active:
            user.is_active = True
            changed_fields.append('is_active')
        if not user.is_staff:
            user.is_staff = True
            changed_fields.append('is_staff')
        if not user.is_superuser:
            user.is_superuser = True
            changed_fields.append('is_superuser')
        if changed_fields:
            user.save(update_fields=changed_fields)
        UserProfile.objects.update_or_create(
            user=user,
            defaults={'tab_permissions': full_permissions, 'allowed_tabs': []},
        )


def rollback_tab_permissions(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.tab_permissions = {}
        profile.save(update_fields=['tab_permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tab_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(migrate_allowed_tabs_to_tab_permissions, rollback_tab_permissions),
    ]
