# Generated by Django 6.1.1 on 2026-09-03 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('bank', 'Bank'), ('item_category', 'Item category'), ('item_condition', 'Item condition'), ('item_unit', 'Item unit')], max_length=40)),
                ('label', models.CharField(max_length=160)),
                ('value', models.SlugField(max_length=180)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'label'],
                'indexes': [models.Index(fields=['group', 'is_active'], name='catalog_dro_group_3310b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'label'), name='unique_option_label_per_group'), models.UniqueConstraint(fields=('group', 'value'), name='unique_option_value_per_group')],
            },
        ),
    ]
