# Generated by Django 6.1.1 on 2026-09-04 13:51

from django.db import migrations, models
from django.utils.text import slugify


PART_NAMES = [
    'Toyota headlight pair',
    'Honda front bumper',
    'Nissan alternator',
    'Mazda side mirror',
    'Suzuki tail light',
    'Engine assembly',
    'Transmission',
    'ABS pump',
    'Shock set',
]


def seed_part_names(apps, schema_editor):
    DropdownOption = apps.get_model('catalog', 'DropdownOption')
    for index, label in enumerate(PART_NAMES):
        DropdownOption.objects.update_or_create(
            group='part_name',
            value=slugify(label),
            defaults={
                'label': label,
                'is_system': True,
                'is_active': True,
                'sort_order': index,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_default_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownoption',
            name='group',
            field=models.CharField(choices=[('bank', 'Bank'), ('part_name', 'Part name'), ('item_category', 'Item category'), ('item_condition', 'Item condition'), ('item_unit', 'Item unit')], max_length=40),
        ),
        migrations.RunPython(seed_part_names, migrations.RunPython.noop),
    ]
