# Generated by Django 6.1.1 on 2026-09-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_item_condition_dropdown_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownoption',
            name='group',
            field=models.CharField(choices=[('bank', 'Bank'), ('part_name', 'Part name'), ('item_category', 'Item category'), ('item_unit', 'Item unit'), ('container_size_type', 'Container size / type')], max_length=40),
        ),
    ]
