# Generated by Django 6.1.1 on 2026-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_dropdownoption_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownoption',
            name='group',
            field=models.CharField(choices=[('bank', 'Bank'), ('part_name', 'Part name'), ('item_category', 'Item category'), ('item_unit', 'Item unit'), ('container_size_type', 'Container size / type'), ('expense_title', 'Expense title'), ('expense_category', 'Expense category'), ('expense_payee', 'Expense payee'), ('expense_payment_method', 'Expense payment method')], max_length=40),
        ),
    ]
