# Generated by Django 6.1.1 on 2026-09-03 18:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_number', models.CharField(max_length=40, unique=True)),
                ('sale_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('cheque', 'Cheque'), ('mixed', 'Mixed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_auction_sales', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('origin_country', models.CharField(blank=True, max_length=80)),
                ('supplier_name', models.CharField(blank=True, max_length=180)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('manifest_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('receiving', 'Receiving'), ('ready_for_auction', 'Ready for auction'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-arrival_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=80)),
                ('part_name', models.CharField(max_length=180)),
                ('part_number', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('condition', models.CharField(choices=[('unknown', 'Unknown'), ('used', 'Used'), ('new', 'New'), ('damaged', 'Damaged')], default='unknown', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='piece', max_length=30)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('gate_pass_issued', 'Gate pass issued'), ('released', 'Released'), ('void', 'Void')], default='available', max_length=30)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.container')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['container__reference', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='AuctionSaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='operations.auctionsale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_line', to='operations.containeritem')),
            ],
            options={
                'ordering': ['sale__sale_number', 'item__lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cnic_or_tax_id', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='auctionsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_sales', to='operations.customer'),
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gate_pass_number', models.CharField(max_length=40, unique=True)),
                ('issued_to_name', models.CharField(max_length=180)),
                ('issued_to_phone', models.CharField(blank=True, max_length=40)),
                ('vehicle_number', models.CharField(blank=True, max_length=80)),
                ('driver_name', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_gate_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='GatePassLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='operations.gatepass')),
                ('sale_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gate_pass_line', to='operations.auctionsaleline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gate_pass__gate_pass_number'],
            },
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['reference'], name='operations__referen_f6e6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['status'], name='operations__status_d36c22_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['arrival_date'], name='operations__arrival_72ab59_idx'),
        ),
        migrations.AddIndex(
            model_name='containeritem',
            index=models.Index(fields=['status'], name='operations__status_4fd73e_idx'),
        ),
        migrations.AddIndex(
            model_name='containeritem',
            index=models.Index(fields=['part_name'], name='operations__part_na_4efda0_idx'),
        ),
        migrations.AddIndex(
            model_name='containeritem',
            index=models.Index(fields=['part_number'], name='operations__part_nu_27af24_idx'),
        ),
        migrations.AddIndex(
            model_name='containeritem',
            index=models.Index(fields=['category'], name='operations__categor_b2c64a_idx'),
        ),
        migrations.AddConstraint(
            model_name='containeritem',
            constraint=models.UniqueConstraint(fields=('container', 'lot_number'), name='unique_lot_per_container'),
        ),
        migrations.AddIndex(
            model_name='auctionsaleline',
            index=models.Index(fields=['sold_price'], name='operations__sold_pr_518cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='operations__name_0185a3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='operations__phone_c7b804_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='operations__is_acti_b925b7_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionsale',
            index=models.Index(fields=['sale_number'], name='operations__sale_nu_f7bee0_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionsale',
            index=models.Index(fields=['sale_date'], name='operations__sale_da_f70e82_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionsale',
            index=models.Index(fields=['payment_type'], name='operations__payment_1858b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionsale',
            index=models.Index(fields=['is_cancelled'], name='operations__is_canc_859e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['gate_pass_number'], name='operations__gate_pa_63bc43_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['status'], name='operations__status_f3f16c_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['issued_at'], name='operations__issued__d17a9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatepassline',
            constraint=models.UniqueConstraint(fields=('sale_line',), name='unique_gate_pass_per_sold_item'),
        ),
    ]
