# Generated by Django 6.1.1 on 2026-09-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='print_status',
            field=models.CharField(choices=[('not_printed', 'Not printed'), ('printed', 'Printed')], default='not_printed', max_length=20),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
