# Generated by Django 6.1.1 on 2026-09-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_gatepass_print_status_gatepass_printed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeritem',
            name='condition',
            field=models.CharField(default='unknown', max_length=80),
        ),
    ]
