# Generated by Django 6.1.1 on 2026-09-03 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_containeritem_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsaleline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_pass', to='operations.auctionsale'),
        ),
        migrations.AlterField(
            model_name='auctionsaleline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='operations.containeritem'),
        ),
        migrations.AddIndex(
            model_name='auctionsaleline',
            index=models.Index(fields=['item'], name='operations__item_id_34a6af_idx'),
        ),
        migrations.AddConstraint(
            model_name='auctionsaleline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_line_quantity_positive'),
        ),
    ]
