# Generated by Django 6.1.1 on 2026-09-04 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_container_items_to_parts(apps, schema_editor):
    ContainerItem = apps.get_model('operations', 'ContainerItem')
    PartInventory = apps.get_model('operations', 'PartInventory')
    AuctionSaleLine = apps.get_model('operations', 'AuctionSaleLine')

    for item in ContainerItem.objects.order_by('created_at', 'id'):
        payload = {
            'part_name': item.part_name,
            'part_number': item.part_number or '',
            'category': item.category or '',
            'condition': item.condition or '',
            'unit': item.unit or 'piece',
        }
        part = PartInventory.objects.filter(**payload).first()
        if part is None:
            part = PartInventory.objects.create(
                id=item.id,
                description=item.description or '',
                quantity=item.quantity,
                reserve_price=item.reserve_price,
                created_by_id=item.created_by_id,
                updated_by_id=item.updated_by_id,
                **payload,
            )
        else:
            update_fields = ['quantity', 'updated_at']
            part.quantity = part.quantity + item.quantity
            if not part.description and item.description:
                part.description = item.description
                update_fields.append('description')
            if part.reserve_price is None and item.reserve_price is not None:
                part.reserve_price = item.reserve_price
                update_fields.append('reserve_price')
            part.save(update_fields=update_fields)
        AuctionSaleLine.objects.filter(item_id=item.id).update(part_inventory_id=part.id)


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auctionsaleline_quantity_gatepass_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_name', models.CharField(max_length=180)),
                ('part_number', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('condition', models.CharField(blank=True, max_length=80)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='piece', max_length=30)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['part_name', 'part_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='auctionsaleline',
            options={'ordering': ['sale__sale_number', 'item__part_name']},
        ),
        migrations.AlterModelOptions(
            name='containeritem',
            options={'ordering': ['container__reference', 'part_name', 'lot_number']},
        ),
        migrations.RemoveConstraint(
            model_name='containeritem',
            name='unique_lot_per_container',
        ),
        migrations.RemoveIndex(
            model_name='containeritem',
            name='operations__status_4fd73e_idx',
        ),
        migrations.AlterField(
            model_name='containeritem',
            name='lot_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='containeritem',
            name='condition',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='partinventory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partinventory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionsaleline',
            name='part_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.partinventory'),
        ),
        migrations.RunPython(migrate_container_items_to_parts, noop),
        migrations.RemoveField(
            model_name='auctionsaleline',
            name='item',
        ),
        migrations.RenameField(
            model_name='auctionsaleline',
            old_name='part_inventory',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='auctionsaleline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='operations.partinventory'),
        ),
        migrations.AddIndex(
            model_name='partinventory',
            index=models.Index(fields=['part_name'], name='operations__part_na_9e4184_idx'),
        ),
        migrations.AddIndex(
            model_name='partinventory',
            index=models.Index(fields=['part_number'], name='operations__part_nu_c6d393_idx'),
        ),
        migrations.AddIndex(
            model_name='partinventory',
            index=models.Index(fields=['category'], name='operations__categor_414ec4_idx'),
        ),
        migrations.AddConstraint(
            model_name='partinventory',
            constraint=models.UniqueConstraint(fields=('part_name', 'part_number', 'category', 'condition', 'unit'), name='unique_sellable_part_inventory'),
        ),
        migrations.AddConstraint(
            model_name='partinventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='part_inventory_quantity_non_negative'),
        ),
    ]
