# Generated by Django 6.1.1 on 2026-09-05 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_partinventory_alter_auctionsaleline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='added_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='containeritem',
            name='raw_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
