# Generated by Django 6.1.1 on 2026-09-05 19:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _part_filter_from_container_item(container_item):
    return {
        'part_name': container_item.part_name,
        'part_number': container_item.part_number or '',
        'category': container_item.category or '',
        'condition': container_item.condition or '',
        'unit': container_item.unit or 'piece',
    }


def _net_unit_cost(container_item, ContainerItem):
    if not container_item.quantity:
        return Decimal('0.00')
    item_raw_total = Decimal(container_item.raw_unit_cost or 0) * Decimal(container_item.quantity)
    if item_raw_total <= 0:
        return Decimal(container_item.raw_unit_cost or 0)

    container_items = ContainerItem.objects.filter(container_id=container_item.container_id)
    container_raw_total = sum(
        (
            Decimal(item.raw_unit_cost or 0) * Decimal(item.quantity or 0)
            for item in container_items
        ),
        Decimal('0.00'),
    )
    if container_raw_total <= 0:
        return Decimal(container_item.raw_unit_cost or 0)

    added_cost = Decimal(container_item.container.added_cost or 0)
    added_share_total = added_cost * (item_raw_total / container_raw_total)
    return Decimal(container_item.raw_unit_cost or 0) + (added_share_total / Decimal(container_item.quantity))


def backfill_inventory_batches(apps, schema_editor):
    AuctionSaleLine = apps.get_model('operations', 'AuctionSaleLine')
    ContainerItem = apps.get_model('operations', 'ContainerItem')
    InventoryBatch = apps.get_model('operations', 'InventoryBatch')
    PartInventory = apps.get_model('operations', 'PartInventory')

    for container_item in ContainerItem.objects.select_related('container').order_by('container__reference', 'created_at'):
        part = PartInventory.objects.filter(**_part_filter_from_container_item(container_item)).first()
        if part is None:
            part = PartInventory.objects.create(
                **_part_filter_from_container_item(container_item),
                quantity=container_item.quantity,
                reserve_price=container_item.reserve_price,
                description=container_item.description or '',
                created_by_id=container_item.created_by_id,
                updated_by_id=container_item.updated_by_id,
            )
        InventoryBatch.objects.update_or_create(
            container_item=container_item,
            defaults={
                'item': part,
                'container': container_item.container,
                'source_label': container_item.container.reference,
                'quantity': container_item.quantity,
                'raw_unit_cost': container_item.raw_unit_cost,
                'notes': container_item.description or '',
                'created_by_id': container_item.created_by_id,
                'updated_by_id': container_item.updated_by_id,
            },
        )

    for part in PartInventory.objects.all().order_by('part_name', 'created_at'):
        container_quantity = (
            InventoryBatch.objects
            .filter(item=part, container__isnull=False)
            .aggregate(total=models.Sum('quantity'))['total']
            or 0
        )
        manual_quantity = max(int(part.quantity or 0) - int(container_quantity), 0)
        if manual_quantity:
            InventoryBatch.objects.create(
                item=part,
                source_label='Manual adjustment',
                quantity=manual_quantity,
                raw_unit_cost=Decimal('0.00'),
                created_by_id=part.created_by_id,
                updated_by_id=part.updated_by_id,
            )

    for sale_line in (
        AuctionSaleLine.objects
        .select_related('sale', 'item')
        .filter(inventory_batch__isnull=True)
        .order_by('sale__sale_date', 'sale__created_at', 'created_at')
    ):
        batches = InventoryBatch.objects.filter(item_id=sale_line.item_id).select_related('container_item', 'container').order_by('container__reference', 'created_at')
        selected_batch = None
        for batch in batches:
            assigned_quantity = (
                AuctionSaleLine.objects
                .filter(inventory_batch=batch, sale__is_cancelled=False)
                .aggregate(total=models.Sum('quantity'))['total']
                or 0
            )
            if int(batch.quantity or 0) - int(assigned_quantity) >= int(sale_line.quantity or 0):
                selected_batch = batch
                break
        if selected_batch is None:
            selected_batch = InventoryBatch.objects.create(
                item_id=sale_line.item_id,
                source_label='Legacy sale allocation',
                quantity=sale_line.quantity,
                raw_unit_cost=Decimal('0.00'),
                created_by_id=sale_line.created_by_id,
                updated_by_id=sale_line.updated_by_id,
            )

        sale_line.inventory_batch = selected_batch
        sale_line.raw_unit_cost_snapshot = selected_batch.raw_unit_cost or Decimal('0.00')
        if selected_batch.container_item_id:
            sale_line.net_unit_cost_snapshot = _net_unit_cost(selected_batch.container_item, ContainerItem)
        else:
            sale_line.net_unit_cost_snapshot = selected_batch.raw_unit_cost or Decimal('0.00')
        sale_line.save(update_fields=['inventory_batch', 'raw_unit_cost_snapshot', 'net_unit_cost_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_container_added_cost_containeritem_raw_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsaleline',
            name='net_unit_cost_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='auctionsaleline',
            name='raw_unit_cost_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_label', models.CharField(blank=True, max_length=180)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('raw_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='operations.container')),
                ('container_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batch', to='operations.containeritem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='operations.partinventory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item__part_name', 'container__reference', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='auctionsaleline',
            name='inventory_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='operations.inventorybatch'),
        ),
        migrations.RunPython(backfill_inventory_batches, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='auctionsaleline',
            index=models.Index(fields=['inventory_batch'], name='operations__invento_5ff3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['item'], name='operations__item_id_004983_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['container'], name='operations__contain_533cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['source_label'], name='operations__source__f411f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_batch_quantity_non_negative'),
        ),
    ]
