# Generated by Django 6.1.1 on 2026-09-07 10:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


MONEY_QUANTUM = Decimal('0.01')


def backfill_statuses_and_net_costs(apps, schema_editor):
    Container = apps.get_model('operations', 'Container')
    ContainerItem = apps.get_model('operations', 'ContainerItem')
    InventoryBatch = apps.get_model('operations', 'InventoryBatch')

    Container.objects.filter(status='draft').update(status='container_bought')
    Container.objects.filter(status='receiving').update(status='godown_loading')

    for container in Container.objects.all().iterator():
        items = list(ContainerItem.objects.filter(container=container).order_by('created_at'))
        raw_total = sum(
            (Decimal(item.raw_unit_cost or 0) * Decimal(item.quantity or 0) for item in items),
            Decimal('0.00'),
        )
        for item in items:
            item_raw_total = Decimal(item.raw_unit_cost or 0) * Decimal(item.quantity or 0)
            if not item.quantity or item_raw_total <= 0 or raw_total <= 0:
                net_unit_cost = Decimal(item.raw_unit_cost or 0).quantize(MONEY_QUANTUM)
            else:
                added_share_total = Decimal(container.added_cost or 0) * (item_raw_total / raw_total)
                net_unit_cost = (
                    Decimal(item.raw_unit_cost or 0) + (added_share_total / Decimal(item.quantity))
                ).quantize(MONEY_QUANTUM)
            ContainerItem.objects.filter(id=item.id).update(net_unit_cost=net_unit_cost)
            InventoryBatch.objects.filter(container_item_id=item.id).update(net_unit_cost=net_unit_cost)

    InventoryBatch.objects.filter(container_item__isnull=True).update(net_unit_cost=models.F('raw_unit_cost'))


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_reserve_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partinventory',
            name='unique_sellable_part_inventory',
        ),
        migrations.AddField(
            model_name='containeritem',
            name='net_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='containeritem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subparts', to='operations.containeritem'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='net_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.RunPython(backfill_statuses_and_net_costs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('container_bought', 'Container Bought'), ('godown_loading', 'Godown Loading'), ('ship_loading', 'Ship Loading'), ('port_loading', 'Port Loading'), ('port_open', 'Port Open'), ('port_close', 'Port Close'), ('edan_gate', 'EDAN Gate'), ('ready_for_auction', 'Ready for auction'), ('closed', 'Closed')], default='container_bought', max_length=30),
        ),
        migrations.AddIndex(
            model_name='containeritem',
            index=models.Index(fields=['parent_item'], name='operations__parent__e210c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='partinventory',
            constraint=models.UniqueConstraint(fields=('part_name', 'part_number', 'category', 'unit'), name='unique_sellable_part_inventory'),
        ),
    ]
