# Generated by Django 6.1.1 on 2026-09-10 14:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_remove_partinventory_unique_sellable_part_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='auctionsale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
