# Generated by Django 6.1.1 on 2026-09-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_align_cheque_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='name_on_cheque',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
