# Generated by Django 6.1.1 on 2026-09-03 23:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_backfill_name_on_cheque'),
        ('operations', '0004_auctionsaleline_quantity_gatepass_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeSettlementAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_allocations', to='finance.cheque')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheque_allocations', to='operations.auctionsale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sale__sale_date', 'created_at'],
                'indexes': [models.Index(fields=['cheque', 'is_reversed'], name='finance_che_cheque__ae5141_idx'), models.Index(fields=['sale', 'is_reversed'], name='finance_che_sale_id_1ac9d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('cheque', 'sale'), name='unique_cheque_allocation_per_sale'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cheque_allocation_amount_positive')],
            },
        ),
    ]
