# Generated by Django 6.1.1 on 2026-09-17 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


DEFAULT_CURRENCIES = [
    ('AED', 'UAE Dirham', 'د.إ'),
    ('AUD', 'Australian Dollar', '$'),
    ('BHD', 'Bahraini Dinar', '.د.ب'),
    ('CAD', 'Canadian Dollar', '$'),
    ('CHF', 'Swiss Franc', 'CHF'),
    ('CNY', 'Chinese Yuan', '¥'),
    ('EUR', 'Euro', '€'),
    ('GBP', 'British Pound', '£'),
    ('HKD', 'Hong Kong Dollar', '$'),
    ('INR', 'Indian Rupee', '₹'),
    ('JPY', 'Japanese Yen', '¥'),
    ('KWD', 'Kuwaiti Dinar', 'د.ك'),
    ('MYR', 'Malaysian Ringgit', 'RM'),
    ('OMR', 'Omani Rial', 'ر.ع.'),
    ('PKR', 'Pakistani Rupee', 'Rs'),
    ('QAR', 'Qatari Riyal', 'ر.ق'),
    ('SAR', 'Saudi Riyal', '﷼'),
    ('SGD', 'Singapore Dollar', '$'),
    ('THB', 'Thai Baht', '฿'),
    ('TRY', 'Turkish Lira', '₺'),
    ('USD', 'US Dollar', '$'),
]


def seed_default_currencies(apps, schema_editor):
    Currency = apps.get_model('finance', 'Currency')
    for code, name, symbol in DEFAULT_CURRENCIES:
        Currency.objects.update_or_create(
            code=code,
            defaults={'name': name, 'symbol': symbol, 'is_system': True, 'is_active': True},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_chequesettlementallocation'),
        ('operations', '0012_backfill_auction_sale_payment_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('payment', 'Payment'), ('cheque_settlement', 'Cheque settlement'), ('cheque_reversal', 'Cheque reversal'), ('write_off', 'Write-off'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=12)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('acquisition_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='finance.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(max_length=40, unique=True)),
                ('payment_date', models.DateField()),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('write_off', 'Write-off / balance adjustment'), ('split', 'Split payment')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.customerpayment'),
        ),
        migrations.CreateModel(
            name='CustomerPaymentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('write_off', 'Write-off / balance adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('cheque', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_component', to='finance.cheque')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='finance.customerpayment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payment__payment_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='operations.auctionsale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.customerpaymentcomponent')),
            ],
            options={
                'ordering': ['sale__sale_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='finance_cur_code_854b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='finance_cur_is_acti_7c20ee_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypurchase',
            index=models.Index(fields=['currency', 'purchase_date'], name='finance_cur_currenc_242c83_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypurchase',
            index=models.Index(fields=['source'], name='finance_cur_source_e9b6ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='currencypurchase',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='currency_purchase_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='currencypurchase',
            constraint=models.CheckConstraint(condition=models.Q(('acquisition_rate__gt', 0)), name='currency_purchase_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='currencypurchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gt', 0)), name='currency_purchase_total_positive'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['payment_number'], name='finance_cus_payment_75b95f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', 'payment_date'], name='finance_cus_custome_270db9_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['kind'], name='finance_cus_kind_506341_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='customer_payment_total_positive'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentcomponent',
            index=models.Index(fields=['method'], name='finance_cus_method_f51b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentcomponent',
            index=models.Index(fields=['bank_name'], name='finance_cus_bank_na_794a41_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_payment_component_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentallocation',
            index=models.Index(fields=['component'], name='finance_cus_compone_ed8bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentallocation',
            index=models.Index(fields=['sale'], name='finance_cus_sale_id_2fb835_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.UniqueConstraint(fields=('component', 'sale'), name='unique_payment_component_allocation_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_amount_positive'),
        ),
        migrations.RunPython(seed_default_currencies, noop_reverse),
    ]
