# Generated by Django 6.1.1 on 2026-09-18 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_customerledgerentry_entry_type_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyOpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('acquisition_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['currency', 'entry_date'], name='finance_cur_currenc_42f25c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='currency_opening_amount_positive'), models.CheckConstraint(condition=models.Q(('acquisition_rate__isnull', True), ('acquisition_rate__gt', 0), _connector='OR'), name='currency_opening_rate_positive_or_null'), models.CheckConstraint(condition=models.Q(('total_cost__isnull', True), ('total_cost__gt', 0), _connector='OR'), name='currency_opening_total_positive_or_null')],
            },
        ),
        migrations.CreateModel(
            name='CurrencySpending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spending_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('purpose', models.CharField(blank=True, max_length=180)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spending_entries', to='finance.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spending_date', '-created_at'],
                'indexes': [models.Index(fields=['currency', 'spending_date'], name='finance_cur_currenc_92c2e4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='currency_spending_amount_positive')],
            },
        ),
    ]
