# Generated by Django 6.1.1 on 2026-09-18 11:14

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def consolidate_duplicate_opening_balances(apps, schema_editor):
    CurrencyOpeningBalance = apps.get_model('finance', 'CurrencyOpeningBalance')
    duplicate_currency_ids = (
        CurrencyOpeningBalance.objects
        .values('currency_id')
        .annotate(entry_count=Count('id'))
        .filter(entry_count__gt=1)
        .values_list('currency_id', flat=True)
    )
    for currency_id in duplicate_currency_ids:
        entries = list(
            CurrencyOpeningBalance.objects
            .filter(currency_id=currency_id)
            .order_by('entry_date', 'created_at', 'id')
        )
        keeper, duplicates = entries[0], entries[1:]
        keeper.amount = sum((entry.amount for entry in entries), Decimal('0.0000'))
        if all(entry.total_cost is not None for entry in entries):
            keeper.total_cost = sum((entry.total_cost for entry in entries), Decimal('0.00'))
            keeper.acquisition_rate = (keeper.total_cost / keeper.amount).quantize(Decimal('0.000001'))
        else:
            keeper.total_cost = None
            keeper.acquisition_rate = None
        notes = list(dict.fromkeys(entry.notes.strip() for entry in entries if entry.notes.strip()))
        keeper.notes = '\n'.join(notes)
        keeper.save(update_fields=['amount', 'total_cost', 'acquisition_rate', 'notes', 'updated_at'])
        CurrencyOpeningBalance.objects.filter(pk__in=[entry.pk for entry in duplicates]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_currencyopeningbalance_currencyspending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(consolidate_duplicate_opening_balances, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='currencyopeningbalance',
            constraint=models.UniqueConstraint(fields=('currency',), name='unique_currency_opening_balance'),
        ),
    ]
