# Generated by Django 6.1.1 on 2026-09-23 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_currencyopeningbalance_unique_currency_opening_balance'),
        ('operations', '0012_backfill_auction_sale_payment_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chequesettlementallocation',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='customerpaymentallocation',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='chequesettlementallocation',
            name='unique_cheque_allocation_per_sale',
        ),
        migrations.RemoveConstraint(
            model_name='customerpaymentallocation',
            name='unique_payment_component_allocation_per_sale',
        ),
        migrations.AddField(
            model_name='chequesettlementallocation',
            name='opening_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_allocations', to='finance.customerledgerentry'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='allocation_mode',
            field=models.CharField(choices=[('overall', 'Overall balance (oldest first)'), ('specific', 'Selected sales or opening balance')], default='overall', max_length=20),
        ),
        migrations.AddField(
            model_name='customerpaymentallocation',
            name='opening_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='finance.customerledgerentry'),
        ),
        migrations.AlterField(
            model_name='chequesettlementallocation',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_allocations', to='operations.auctionsale'),
        ),
        migrations.AlterField(
            model_name='customerpaymentallocation',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='operations.auctionsale'),
        ),
        migrations.AddConstraint(
            model_name='chequesettlementallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('sale__isnull', False)), fields=('cheque', 'sale'), name='unique_cheque_allocation_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='chequesettlementallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('opening_balance__isnull', False)), fields=('cheque', 'opening_balance'), name='unique_cheque_allocation_per_opening'),
        ),
        migrations.AddConstraint(
            model_name='chequesettlementallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opening_balance__isnull', True), ('sale__isnull', False)), models.Q(('opening_balance__isnull', False), ('sale__isnull', True)), _connector='OR'), name='cheque_allocation_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('sale__isnull', False)), fields=('component', 'sale'), name='unique_payment_component_allocation_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('opening_balance__isnull', False)), fields=('component', 'opening_balance'), name='unique_payment_component_allocation_per_opening'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opening_balance__isnull', True), ('sale__isnull', False)), models.Q(('opening_balance__isnull', False), ('sale__isnull', True)), _connector='OR'), name='payment_allocation_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='customerpaymenttarget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerpaymenttarget',
            name='opening_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_targets', to='finance.customerledgerentry'),
        ),
        migrations.AddField(
            model_name='customerpaymenttarget',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='finance.customerpayment'),
        ),
        migrations.AddField(
            model_name='customerpaymenttarget',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_targets', to='operations.auctionsale'),
        ),
        migrations.AddField(
            model_name='customerpaymenttarget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customerpaymenttarget',
            index=models.Index(fields=['payment'], name='finance_cus_payment_c4b055_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymenttarget',
            constraint=models.UniqueConstraint(condition=models.Q(('sale__isnull', False)), fields=('payment', 'sale'), name='unique_payment_target_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymenttarget',
            constraint=models.UniqueConstraint(condition=models.Q(('opening_balance__isnull', False)), fields=('payment', 'opening_balance'), name='unique_payment_target_per_opening'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymenttarget',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_target_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymenttarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opening_balance__isnull', True), ('sale__isnull', False)), models.Q(('opening_balance__isnull', False), ('sale__isnull', True)), _connector='OR'), name='payment_target_exactly_one_receivable'),
        ),
    ]
