# Generated by Django 6.1.1 on 2026-09-24 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_customerpaymenttarget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCreditor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyCreditorRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repayment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-repayment_date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='currencypurchase',
            name='currency_purchase_rate_positive',
        ),
        migrations.RemoveConstraint(
            model_name='currencypurchase',
            name='currency_purchase_total_positive',
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='purchase_type',
            field=models.CharField(choices=[('cash', 'Paid purchase'), ('credit', 'Credit purchase')], default='cash', max_length=12),
        ),
        migrations.AlterField(
            model_name='currencypurchase',
            name='acquisition_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='currencypurchase',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='currencycreditor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencycreditor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to='finance.currencycreditor'),
        ),
        migrations.AddIndex(
            model_name='currencypurchase',
            index=models.Index(fields=['creditor', 'purchase_type'], name='finance_cur_credito_1b764f_idx'),
        ),
        migrations.AddIndex(
            model_name='currencypurchase',
            index=models.Index(fields=['due_date'], name='finance_cur_due_dat_c3820a_idx'),
        ),
        migrations.AddConstraint(
            model_name='currencypurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acquisition_rate__gt', 0), ('creditor__isnull', True), ('purchase_type', 'cash'), ('total_cost__gt', 0)), models.Q(('acquisition_rate__isnull', True), ('creditor__isnull', False), ('purchase_type', 'credit'), ('total_cost__isnull', True)), _connector='OR'), name='currency_purchase_financial_fields_match_type'),
        ),
        migrations.AddField(
            model_name='currencycreditorrepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencycreditorrepayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='finance.currencypurchase'),
        ),
        migrations.AddField(
            model_name='currencycreditorrepayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='currencycreditor',
            index=models.Index(fields=['name'], name='finance_cur_name_2e2f56_idx'),
        ),
        migrations.AddIndex(
            model_name='currencycreditor',
            index=models.Index(fields=['is_active'], name='finance_cur_is_acti_525303_idx'),
        ),
        migrations.AddIndex(
            model_name='currencycreditorrepayment',
            index=models.Index(fields=['purchase', 'repayment_date'], name='finance_cur_purchas_d847eb_idx'),
        ),
        migrations.AddIndex(
            model_name='currencycreditorrepayment',
            index=models.Index(fields=['repayment_date'], name='finance_cur_repayme_cb8a0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='currencycreditorrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='currency_repayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='currencycreditorrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='currency_repayment_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='currencycreditorrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gt', 0)), name='currency_repayment_total_positive'),
        ),
    ]
